###GET ALL USERS
GET http://localhost:4000/users/

###GET USER BY ID
GET http://localhost:4000/users/68b6113e26740e7408313a4b


###CREATE NEW USER
POST http://localhost:4000/users/
Content-Type: application/json

{
    "username": "bryan9",
    "email": "email9@gmail.com",
    "password": "123456"
}

###UPDATE USER
PUT http://localhost:4000/users/68b6113e26740e7408313a4b
Content-Type: application/json

{
    "username": "bryan5",
    "email": "email2@gmail.com",
    "password": "123456"
}

###DELETE USER
DELETE http://localhost:4000/users/68b618afad86d72136179c8c
